<?php

namespace Tests\Models;

use App\Models\Company;
use Tests\TestCase;

class GetNullEmployeesCompaniesTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_取得retry次數小於3的公司()
    {
        $company_data = Company::get_null_employees();
        // 當沒有資料時會回傳 null，有資料時回傳 array
        $this->assertTrue($company_data === null || is_array($company_data));
    }

    public function test_把公司retry次數加1()
    {
        $result = Company::add_retry_times(1);
        $this->assertTrue($result);
    }
}
